"""Git worktree sandbox management and lifecycle."""

from dovo.core.sandbox.exceptions import (
    SandboxCapacityError,
    SandboxConfigError,
    SandboxError,
)
from dovo.core.sandbox.facade import Sandbox
from dovo.core.sandbox.models import (
    PruneAction,
    PrunedItem,
    SandboxApplyResult,
    SandboxApplyStatus,
    SandboxApplyStrategy,
    SandboxCreateResult,
    SandboxCreateStatus,
    SandboxDeleteResult,
    SandboxDeleteStatus,
    SandboxDetectionResult,
    SandboxDetectionStatus,
    SandboxDiffResult,
    SandboxDiffStatus,
    SandboxListResult,
    SandboxListStatus,
    SandboxPruneResult,
    SandboxPruneStatus,
    SandboxSession,
    SandboxShowResult,
    SandboxShowStatus,
    StaleSandboxCategory,
    StaleSandboxItem,
)

__all__ = [
    "PruneAction",
    "PrunedItem",
    "Sandbox",
    "SandboxApplyResult",
    "SandboxApplyStatus",
    "SandboxApplyStrategy",
    "SandboxCapacityError",
    "SandboxConfigError",
    "SandboxCreateResult",
    "SandboxCreateStatus",
    "SandboxDeleteResult",
    "SandboxDeleteStatus",
    "SandboxDetectionResult",
    "SandboxDetectionStatus",
    "SandboxDiffResult",
    "SandboxDiffStatus",
    "SandboxError",
    "SandboxListResult",
    "SandboxListStatus",
    "SandboxPruneResult",
    "SandboxPruneStatus",
    "SandboxSession",
    "SandboxShowResult",
    "SandboxShowStatus",
    "StaleSandboxCategory",
    "StaleSandboxItem",
]
