"""Git worktree management and lifecycle."""

from dovo.core.worktree.exceptions import (
    WorktreeCapacityError,
    WorktreeConfigError,
    WorktreeError,
)
from dovo.core.worktree.models import (
    PruneAction,
    PrunedItem,
    StaleWorktreeCategory,
    StaleWorktreeItem,
    WorktreeApplyResult,
    WorktreeApplyStatus,
    WorktreeApplyStrategy,
    WorktreeCreateResult,
    WorktreeCreateStatus,
    WorktreeDeleteResult,
    WorktreeDeleteStatus,
    WorktreeDetectionResult,
    WorktreeDetectionStatus,
    WorktreeDiffResult,
    WorktreeDiffStatus,
    WorktreeListResult,
    WorktreeListStatus,
    WorktreePruneResult,
    WorktreePruneStatus,
    WorktreeSession,
    WorktreeShowResult,
    WorktreeShowStatus,
)
from dovo.core.worktree.worktree import Worktree

__all__ = [
    "PruneAction",
    "PrunedItem",
    "StaleWorktreeCategory",
    "StaleWorktreeItem",
    "Worktree",
    "WorktreeApplyResult",
    "WorktreeApplyStatus",
    "WorktreeApplyStrategy",
    "WorktreeCapacityError",
    "WorktreeConfigError",
    "WorktreeCreateResult",
    "WorktreeCreateStatus",
    "WorktreeDeleteResult",
    "WorktreeDeleteStatus",
    "WorktreeDetectionResult",
    "WorktreeDetectionStatus",
    "WorktreeDiffResult",
    "WorktreeDiffStatus",
    "WorktreeError",
    "WorktreeListResult",
    "WorktreeListStatus",
    "WorktreePruneResult",
    "WorktreePruneStatus",
    "WorktreeSession",
    "WorktreeShowResult",
    "WorktreeShowStatus",
]
